Repository SangHwi-Back/issue-tracker, pull requests merged in 2022-06, with the labels that each got.

#12 [test] test DIContainer
  IssueTracker15/ContainerUnitTest/ContainerUnitTest.swift
  IssueTracker15/ContainerUnitTest/MockContainer.swift
  IssueTracker15/ContainerUnitTest/MockData.swift
  IssueTracker15/IssueTracker15.xcodeproj/project.pbxproj
  IssueTracker15/IssueTracker15.xcodeproj/xcshareddata/xcschemes/IssueTracker15.xcscheme
  IssueTracker15/IssueTracker15/Test/Container/ContainerWrapper.swift
  IssueTracker15/IssueTracker15/Test/Container/UseCaseContainer.swift
  IssueTracker15/IssueTracker15/Test/UseCases/UseCaseResponsible.swift
Labels: test

#13 로그인 뷰 구현 및 피어세션용 정리.
  IssueTracker15/.swiftlint.yml
  IssueTracker15/ContainerUnitTest/ContainerUnitTest.swift
  IssueTracker15/ContainerUnitTest/MockContainer.swift
  IssueTracker15/IssueTracker15.xcodeproj/project.pbxproj
  IssueTracker15/IssueTracker15/Extension/UIView.swift
  IssueTracker15/IssueTracker15/Info.plist
  IssueTracker15/IssueTracker15/Login/View/OAuthLoginButton.swift
  IssueTracker15/IssueTracker15/Login/View/OAuthLoginStackView.swift
  IssueTracker15/IssueTracker15/Login/View/UserInfoInputStackView.swift
  IssueTracker15/IssueTracker15/Login/ViewController/LoginViewController.swift
  IssueTracker15/IssueTracker15/Login/ViewModel/LoginViewModel.swift
  IssueTracker15/IssueTracker15/RegularExpressionChecker/IDChecker.swift
  IssueTracker15/IssueTracker15/RegularExpressionChecker/PasswordChecker.swift
  IssueTracker15/IssueTracker15/SupportingFiles/Assets.xcassets/githublogo.imageset/Contents.json
  IssueTracker15/IssueTracker15/SupportingFiles/Assets.xcassets/githublogo.imageset/Untitled-1 1 (2).png
  IssueTracker15/IssueTracker15/SupportingFiles/Assets.xcassets/githublogo.imageset/Untitled-1 1 (3).png
  IssueTracker15/IssueTracker15/SupportingFiles/Assets.xcassets/githublogo.imageset/Untitled-1 1 (4).png
  IssueTracker15/IssueTracker15/SupportingFiles/SceneDelegate.swift
  IssueTracker15/IssueTracker15/Test/Container/ContainerWrapper.swift
  IssueTracker15/IssueTracker15/Test/UseCases/TestUseCase.swift
  IssueTracker15/IssueTracker15/Test/UseCases/UseCaseResponsible.swift
  IssueTracker15/IssueTracker15/Test/Views/TestButton.swift
  IssueTracker15/IssueTracker15/Test/Views/TestLabel.swift
  IssueTracker15/IssueTracker15/ViewController.swift
Labels: enhancement, feature

#14 [Feature] network Layer 중간작업 PR
  IssueTracker15/IssueTracker15.xcodeproj/project.pbxproj
  IssueTracker15/IssueTracker15.xcodeproj/xcshareddata/xcschemes/IssueTracker15.xcscheme
  IssueTracker15/IssueTracker15/Repository/Network/NetworkService.swift
  IssueTracker15/IssueTracker15/Repository/Persistent/PersistentService.swift
  IssueTracker15/IssueTracker15/Repository/Repository.swift
  IssueTracker15/IssueTracker15/Repository/ServiceContainer.swift
  IssueTracker15/IssueTracker15/Repository/Transferable.swift
  IssueTracker15/IssueTracker15/Test/UseCases/RequestModel.swift
  IssueTracker15/IssueTracker15/Test/UseCases/TestDecodableType.swift
  IssueTracker15/IssueTracker15/Test/UseCases/TestUseCase.swift
  IssueTracker15/IssueTracker15/Test/UseCases/UseCaseModel.swift
  IssueTracker15/IssueTracker15/Test/ViewModel/TestViewModel.swift
  IssueTracker15/ViewModelUnitTest/ViewModelUnitTest.swift
Labels: test, refactoring, feature

#15 Feature/service generic
  IssueTracker15/IssueTracker15/Repository/Network/NetworkService.swift
  IssueTracker15/IssueTracker15/Repository/Repository.swift
  IssueTracker15/IssueTracker15/Repository/ServiceContainer.swift
  IssueTracker15/IssueTracker15/Test/UseCases/RequestModel.swift
  IssueTracker15/IssueTracker15/Test/UseCases/TestUseCase.swift
Labels: enhancement, feature

#17 Feature/issue mock list
  IssueTracker15/IssueTracker15.xcodeproj/project.pbxproj
  IssueTracker15/IssueTracker15/IssueList/DTO/IssueDTO.swift
  IssueTracker15/IssueTracker15/IssueList/DTO/LabelDTO.swift
  IssueTracker15/IssueTracker15/IssueList/DTO/MilestoneDTO.swift
  IssueTracker15/IssueTracker15/IssueList/DTO/PullRequestDTO.swift
  IssueTracker15/IssueTracker15/IssueList/DTO/UserDTO.swift
  IssueTracker15/IssueTracker15/IssueList/View/IssueListCell.swift
  IssueTracker15/IssueTracker15/IssueList/View/IssueListFooterReusableView.swift
  IssueTracker15/IssueTracker15/IssueList/View/IssueListHeaderReusableView.swift
  IssueTracker15/IssueTracker15/IssueList/View/IssueListViewController.swift
  IssueTracker15/IssueTracker15/IssueList/ViewModel/IssueViewModel.swift
  IssueTracker15/IssueTracker15/IssueNavigationController.swift
  IssueTracker15/IssueTracker15/LabelNavigationController.swift
  IssueTracker15/IssueTracker15/MainTabBarController.swift
  IssueTracker15/IssueTracker15/MilestoneNavigationController.swift
  IssueTracker15/TestIssueList.json
  IssueTracker15/TestLabels.json
Labels: feature

#21 IssueListCell 레이아웃 & Select 기능
  IssueTracker15/IssueTracker15.xcodeproj/project.pbxproj
  IssueTracker15/IssueTracker15/Filter/IssueFilterItemSelectViewController.swift
  IssueTracker15/IssueTracker15/IssueList/DTO/IssueDTO.swift
  IssueTracker15/IssueTracker15/IssueList/View/IssueListCell.swift
  IssueTracker15/IssueTracker15/IssueList/View/IssueListHeaderReusableView.swift
  IssueTracker15/IssueTracker15/IssueList/View/IssueListViewController.swift
  IssueTracker15/IssueTracker15/IssueList/ViewModel/IssueViewModel.swift
  IssueTracker15/IssueTracker15/SupportingFiles/UIImage+SFSymbol.swift
Labels: feature

#32 [Feature] Issue List Swipe and Bar button Action
  IssueTracker15/IssueTracker15.xcodeproj/project.pbxproj
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListFooterReusableView.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListHeaderReusableView.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListSearchBar.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListTableViewCell.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListTableViewController.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListTableViewDataSource.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListTableViewDelegate.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListViewController.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/ViewModel/IssueViewModel.swift
  IssueTracker15/IssueTracker15/Issue/IssueNavigationController.swift
  IssueTracker15/IssueTracker15/MainTabBarController.swift
  IssueTracker15/IssueTracker15/SupportingFiles/SceneDelegate.swift
Labels: enhancement, feature

#38 Feature/ Issue label
  IssueTracker15/IssueTracker15.xcodeproj/project.pbxproj
  IssueTracker15/IssueTracker15/Label/AddLabelViewController.swift
  IssueTracker15/IssueTracker15/Label/IssueLabelDataSource.swift
  IssueTracker15/IssueTracker15/Label/LabelNavigationController.swift
  IssueTracker15/IssueTracker15/Label/LabelViewController.swift
  IssueTracker15/IssueTracker15/Label/View/AddLabelBarButtonItem.swift
  IssueTracker15/IssueTracker15/Label/View/IssueTitleButton.swift
  IssueTracker15/IssueTracker15/Label/View/LabelTableViewCell.swift
  IssueTracker15/IssueTracker15/Login/ViewModel/LoginViewModel.swift
  IssueTracker15/IssueTracker15/MainTabBarController.swift
  IssueTracker15/IssueTracker15/SupportingFiles/AppDelegate.swift
Labels: feature
